name: Integration tests

on:
  pull_request:

jobs:
  coverage:
    name: Integration tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sdk
        uses: actions/checkout@v3
        with:
          path: 'sdk'
      - name: Checkout mantle
        uses: actions/checkout@v3
        with:
          repository: mantlenetworkio/mantle
          submodules: 'recursive'
          path: 'mantle'
          ref: 'v2.0.0'
      - name: Setup node/yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install dependencies
        run: |
          cd sdk
          yarn
          yarn build
      - name: Start background mantle test-node.bash
        run: |
          cd mantle
          ./test-node.bash --init --no-blockscout &
      - name: Copy .env
        run: |
          cd sdk
          cp ./.env-sample ./.env
      - name: Wait for mantle startup
        run: |
          cd sdk/scripts
          ./waitForMantle.sh
      - name: Generate network file
        run: |
          cd sdk
          yarn gen:network
      - name: Integration tests
        run: |
          cd sdk
          CI=true yarn test:integration
